# Generated by Django 4.0.6 on 2022-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr_cert', '0002_alter_csr_csr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csr',
            name='key',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
