# Generated by Django 4.0.5 on 2022-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr_cert', '0006_alter_csr_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr',
            name='common_name',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='csr',
            name='name',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
